name: 'Publish package to NPM'

description: 'Check diff, build package, edit version, add tag, publish to npm'

inputs:
  github-token:
    description: GitHub token used to make API requests.
    default: ${{ github.token }}
    required: true
  package-path:
    description: Package path.
    default: ''
    required: true

outputs:
  time: # id of output
    description: 'The time we greeted you'

runs:
  using: 'node12'
  main: 'dist/index.js'
