name: Beta publish to NPM

on:
  push:
    branches: [ beta, stg*, hotfix* ]

  pull_request:
    types: [ closed ]
    branches: [ stg*, hotfix* ]

jobs:
  check_version_and_publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Check @coolwallet/core
      uses: ./.github/publish-action
      with:
        package-path: 'packages/core/'

    - name: Check @coolwallet/btc
      uses: ./.github/publish-action
      with:
        package-path: 'packages/cws-btc/'
